---
# Source: kubeinvaders/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": "pre-install"
  name: kubeinvaders
  namespace: kubeinvaders
  labels:
    app: kubeinvaders
    chart: kubeinvaders
    release: kubeinvaders
    heritage: Helm
