---
# Source: kubeinvaders/templates/secrets.yaml
kind: Secret
apiVersion: v1
metadata:
  labels:
    app: kubeinvaders
    chart: kubeinvaders
    release: kubeinvaders
    heritage: Helm
  name: kubeinvaders-token
  namespace: kubeinvaders
  annotations:
    kubernetes.io/service-account.name: kubeinvaders
type: kubernetes.io/service-account-token
