---
# Source: kubeinvaders/templates/clusterrole-binding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeinvaders
  namespace: kubeinvaders
  labels:
    app: kubeinvaders
    chart: kubeinvaders-0.1.0
    release: kubeinvaders
    heritage: Helm
subjects:
- kind: ServiceAccount
  name: kubeinvaders
  namespace: kubeinvaders
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeinvaders
